name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/setup-go@v2-beta
            with:
              go-version: 1.15
          - uses: actions/checkout@v2
          - run: make test
